dataset: clinc150
intent_num: 150
gpu: 1
timestamp: '2021-01_22-8_27'
repeat: 1
scale: 1000
damp: 0.003
recursion: -1
param_path: ''
aupr_out: 0.0
ratio: 0.1
batch_size: 512  # for rep
regenerate: 0
seed: 2222

ith: 0
split_num: 4

loss: energy
m_in: -8.
m_out: -5.

gamma: 20

option: 'prepare_s'  # prepare_s or cal_inf 